@baseUrl = http://localhost:3000/api

GET {{baseUrl}}/entries

###

POST {{baseUrl}}/entries
Content-Type: application/json

{
  "text": "I walk around like everything’s fine, but deep down, inside my shoe, my sock is sliding off.",
  "author": "Anonymous"
}